function fetchQuote() {

  return ["My fake plants died because I did not pretend to water them.",
    "I wanted to buy a candle holder, but the store didn't have one. So I got a cake.",
    "Rice is great if you're really hungry and want to eat two thousand of something.",
    "My belt holds my pants up, but the belt loops hold my belt up. I don't really know what's happening down there. Who is the real hero?",
    "I'm against picketing, but I don't know how to show it.",
    "A waffle is like a pancake with a syrup trap.",
    "I think foosball is a combination of soccer and shish kabobs.",
    "I would imagine that if you could understand Morse code, a tap dancer would drive you crazy.",
    "A severed foot is the ultimate stocking stuffer.",
    "Wearing a turtleneck is like being strangled by a really weak guy, all day.",
    "I bought a doughnut and they gave me a receipt for the doughtnut... I don't need a receipt for the doughnut. I give you money and you give me the doughnut, end of transaction. We don't need to bring ink and paper into this. I can't imagine a scenario that I would have to prove that I bought a doughnut.",
    "I used to do drugs. I still do drugs. But I used to, too.",
    "Is a hippopotamus a hippopotamus, or just a really cool Opotamus?",
    "I went to the airport, I put my bag in the x-ray machine, I found out my bag has cancer. It only has six more months to hold stuff.",
    "A sleeping bag is a tortilla for a human.",
    "I've never been to a hotel with a rotating restaurant on top, but one time I took my girlfriend to a merry-go-round, and I gave her a burrito.",
    "I went to the store and bought eight apples; the clerk said, \"Do you want these in a bag?\" I said, \"Oh, no, man, I juggle.\"",
    "I had a job interview at an insurance company once and the lady said 'Where do you see yourself in five years?' I said 'Celebrating the fifth year anniversary of you asking me this question.'",
    "I order the club sandwich all the time. And I'm not even a member, man. I don't know how I get away with it.",
    "My lucky number is four billion. That doesn't come in real handy when you're gambling. 'Come on, four billion. Fuck. Seven. Not even close.'",
    "I got an idea for sweat shops... air conditioning. Problem solved.",
    "I find a duck’s opinion of me is very much influenced by whether or not I have bread.",
    "I’d hate to be a giraffe with a sore throat.",
    "I was gonna have my teeth whitened, but then I said fuck that, I’ll just get a tan instead.",
    "I walked by a dry cleaner at 3am, the sign said 'Sorry we're closed.' You don't have to be sorry; it's 3am and you're a dry cleaner. It would be ridiculous for me to expect you to be open. I'm not gonna walk in at 10am and say \'Hey, I walked by at 3, you guys were closed. Somebody owes me an apology.'",
    "I like to take a toothpick and throw it in the forest and say 'You're home!'",
    "If I'm out to dinner with a group of friends and someone offers to pay for the check, I immediately reach for my wallet. Because inside is a note that says 'Say thanks.'",
    "An escalator can never break; it can only become stairs.",
    "I want to get a job naming kitchen appliances. That seems easy, you know? Refrigerator, toaster, blender. You just say what the thing does, then you add 'er.'",
    "I don't have a girlfriend. I just know a girl who would get really mad if she heard me say that."];

};
